### ISSUE TITLE
Verify UK Laptop Inventory (Tracking)

### ISSUE THREAD

**Issue by MattCFry** [CodeYourFuture/CYF-Staff-Tickets#567]
### Background

We need to enter all of our records into the new system as part of [this milestone](https://github.com/CodeYourFuture/CYF-Staff-Tickets/milestone/20) before we can roll it out for global usage.

Many global records need verifying before entering the new system as usable records. 

### Acceptance criteria

- [x] All regions have identified those on their laptop inventory which should be contacted.
- [ ] (Matt) The people identified should be contacted via mail merge. 
- [ ] (Matt) Any info collected should be updated on the existing records.

A week after the mail merge for a region has been sent, the work in that region can be considered complete. Please see below for progress. Any residual info acquired will need to be done on an ad-hoc basis.

### Owner

@mattcfry

### Stakeholder

@CodeYourFuture/programme-managers and @Barny-6 

### Approver

@mattcfry

**Regional Progress**

West Midlands
- [x] Contact list on existing records made.
- [ ] Mail merge sent
- [ ] Closed

London
- [x] Contact list on existing records made.
- [ ] Mail merge sent
- [ ] Closed

Scotland
- [ ] Contact list on existing records made.
- [ ] Mail merge sent
- [ ] Closed

North West
- [ ] Contact list on existing records made.
- [ ] Mail merge sent
- [ ] Closed

**Comment by MattCFry** [comment]
West Midlands
- [ ] Contact list on existing records made.
- [ ] Mail merge sent
- [ ] Closed

London
- [ ] Contact list on existing records made.
- [ ] Mail merge sent
- [ ] Closed

Scotland
- [ ] Contact list on existing records made.
- [ ] Mail merge sent
- [ ] Closed

North West
- [ ] Contact list on existing records made.
- [ ] Mail merge sent
- [ ] Closed

**Comment by haldenb** [comment]
Have put time i my calendar Friday to verify records and then will work out this mail merge of which you speak :D

**Comment by MattCFry** [comment]
I'll take on the mail merging @haldenb. I just need a list of names to contact ❤️

**Comment by ShaunCYFSA** [comment]
@MattCFry - I have a mail merge template if you need one. Secondly, do you have a template setup on Airtable to capture the laptop data?

**Comment by MattCFry** [comment]
@ShaunCYFSA I already put one together :( we should compare and keep one for going forward. 

I don't because I don't think it can do that. Questions
1. Are you onboarded to airtable?
2. Does ZA now have laptops to loan out?

**Comment by ShaunCYFSA** [comment]
@MattCFry - I would love to use the same template that you have. 
I have been onboarded to Airtable.
ZA still needs to get loan laptops but happy to populate with a single row of dummy data.

**Comment by MattCFry** [comment]
@ShaunCYFSA for now I would leave it. If you could make a location for where you will keep your laptop storge then that would be amazing. Let's discuss this on slack to not bulk out this ticket :)

**Comment by emcglackenr1** [comment]
Potentially relates to **Update laptop inventory Scotland** 
[#569](https://github.com/CodeYourFuture/CYF-Staff-Tickets/issues/569)

**Comment by emcglackenr1** [comment]
**Questions**
**1. How do we know who 'should be contacted' in this context?**
My understanding from our chat is that it means anyone whose name is associated with a laptop. The priority are ones that we expected to be returned but haven't been. 
A secondary consideration might be laptops currently in use. 

**2. Are you asking PROMS to put contact details (email) in the laptop spreadsheet for you?** 
The Scotland inventory currently only has first names and class. Details can be found on the global trainees spreadsheet, but let me know if you would like me to copy paste this for you.

**Comment by MattCFry** [comment]
@emcglackenr1 

1. Yes. Anyone who is associated with a laptop record which we know is either loaned out or a record where we don't know if this person still has a laptop.

2. No, no emails in that spreadsheet. I just need the full name of the person. 

Other bits that will help me are cohort (just so I have a reference) and email. If you don't have time to get the extra bits, then that's fine. If you are giving me extra bits, then maybe sending me what you have through an email will prevent email addresses from being posted everywhere.

**Comment by MattCFry** [comment]
Im closing this ticket as a tracking ticket is no longer worth the effort
