### ISSUE TITLE
Code Division Collaboration - Sprint 14

### ISSUE THREAD

**Issue by emcglackenr1** [CodeYourFuture/CYF-Staff-Tickets#606]
**Summary** 
CYF have a close relationship with Code Division, and we currently share an office space in Glasgow in Princes House. There is ongoing collaboration with Code Division through Germán in terms of partnerships and Dara in terms of Glasgow / Scotland based activities. 

All of the information for the meeting that created these actions is in the 
-[ collaborative document](https://docs.google.com/document/d/1tsQ3W7a49nxzaKi3n6GmiRnwcKhAu5_x0UrJaH9I9rI/edit#heading=h.nz9f2p6sxi4i)

**Completion Criteria**
These tasks are based on actions from the collaborative doc. Some might be better added to a different / new issue.

**DLP**
Frank discussed that his contacts expressed a need for a course like DLP for the group of over 5,000 refugees in Glasgow.
- [x] Intro Frank to Amy - for DLP relates to #541 
- [x] Move DLP info to issue / develop issue #541  (e.g. develop GLA DLP Milestone) and convert this section to notes
- [x] Dara to meet @AmyCYF to discuss

**Potential Grant**
Frank mentioned a grant that CD have applied for that might be helpful for CYF. Any event might have to be based in Dundee.
Org: DigiTay, the Tay Cities Region Digital Skills Project is launching a [Third Sector Digital Skills Challenge Fund](https://www.digitay.scot/funding-opportunities/).
- [x] Look into if Grant is suitable for CYF  - It's not
- [x] Update Frank 

**JP Morgan Discussions**
- [x] Discuss event with Germán
- [x] Create a new ticket - #634 

**Events**

**Joint Event with CYF and CD - Cyber showcase** 
- [x] Discuss joint event with Germán and handover
- [x] Update Frank about handover
- [x] Create issue #635 

**Data Talent**
- [x] Check CYF's plan for the Data Talent event - [done](https://codeyourfuture.slack.com/archives/C04B5106M6U/p1708354186054359)
- [x] Add info to Data Talent Ticket #633 

**Venues** relates to Milestone **[Secure Venue for GLA6 Classes](https://github.com/CodeYourFuture/CYF-Staff-Tickets/milestone/4)**
- [x] Move this to new issue #632
- [x] Contact Clutha Trust about venue move

**Other**
- [x] Intro researcher to CYF volunteer Gianluca

**Comment by SallyMcGrath** [comment]
Let's now update your progress @emcglackenr1 

1. Break out the tickets for other people into new tickets, 
2. Close this ticket  - you did it! It's ✅ Done
