### ISSUE TITLE
Discuss Grad Role and Retention Tracking

### ISSUE THREAD

**Issue by MattCFry** [CodeYourFuture/CYF-Staff-Tickets#607]
### Background

Barny has made progress in these areas. When schedules open up, Matt and Barny should discuss these projects and plan for the future.

### Acceptance criteria

- [x] Matt and Barny schedule a meeting to discuss these projects.
- [x] Barny demos and explains his progress thus far.
- [x] Goals / outcomes agreed.
- [x] Tickets and/or milestones created collaboratively.

### Owner

@mattcfry

### Stakeholder

@Barny-6

### Approver

@Barny-6

**Comment by MattCFry** [comment]
@Barny-6 should we book a time when I'm in Manchester to talk about this? :)

**Comment by Barny-6** [comment]
great idea! I wanted to do this next sprint (which starts when you're up). I'll book something in our calendars

**Comment by Barny-6** [comment]
**Context**
@Barny-6  needs support in collecting data on how alumni are progressing. He's currently getting detailed data from a small amount of alumni through networking work but doesn't have capacity to do manual data collection for all grads. Data collection is/can be done in different ways: 

Manual Searching 
- Linkedin etc. (done on a small scale)

Surveys
- Mass emails etc.  (done occasionally) 

DMing
- LinkedIn / Email  (done on a small scale)

Phone screening

Alumni Network 

We agreed to split the goals into different tickets

**Ticket 1:** Collecting data
Goals
- A % figure on retention over 2 years
- An average retention in first role
- To know where >75% of our alumni have worked

**Ticket 2**: Process for continuous collection of data going forward
Goals 
- Bring together the right people for the project
- Agree on timeframe for updates
- Agree on key goals of updates (thinking about other goals we have when connecting with alumni) 


**Action** to ask Claire for dates sections in Global trainees

**Comment by MattCFry** [comment]
@Barny-6 could you provide a rough priority of groups to focus time on? Using the groups on Global Trainees.

Additionally, what groups do we not need info from?
