### ISSUE TITLE
Creation of tracking spreadsheet for Capgemini contract terms

### ISSUE THREAD

**Issue by lilianabermudes** [CodeYourFuture/CYF-Staff-Tickets#629]
### Background

(Claire, I thought about it yesterday)

CYF and Capgemini signed a new contract with new terms. We should have an easy way to demonstrate how we're progressing with the terms. 

Deadline: March 8th

### Acceptance criteria

- [x] Check the contract terms
- [x] Draft spreadsheet/system that easily demonstrates how we progress with the contract terms
- [x] Approve with Lili
- [ ] Approve with German

### Owner

Claire

### Stakeholder

Liliana

### Approver

German

**Comment by ClaireBickley** [comment]
draft here
[https://docs.google.com/spreadsheets/d/1CAVxV39fWMfEFeAzNlNU1aUfUxPUoTJF1-ieR92NvX8/edit#gid=1709744959](https://docs.google.com/spreadsheets/d/1CAVxV39fWMfEFeAzNlNU1aUfUxPUoTJF1-ieR92NvX8/edit#gid=1709744959)

**Comment by ClaireBickley** [comment]
HI Lili, I've created a [tracking spreadsheet](https://docs.google.com/spreadsheets/d/1CAVxV39fWMfEFeAzNlNU1aUfUxPUoTJF1-ieR92NvX8/edit#gid=1709744959), hope this is what you were looking for. It has test data in at the moment, we can update it and have it pull from Global Trainees when we're ready. Let me know what you think?

**Comment by lilianabermudes** [comment]
I loved it! Left one question
