### ISSUE TITLE
Automate Alumni Progress Tracking

### ISSUE THREAD

**Issue by Barny-6** [CodeYourFuture/CYF-Staff-Tickets#680]
**Context**
Following on from the discussion in https://github.com/CodeYourFuture/CYF-Staff-Tickets/issues/607 and attached to https://github.com/CodeYourFuture/CYF-Staff-Tickets/issues/679

Once we have the data for the current alumni we should look at how we can automate or at least make the process for collecting this data more regular and less painful. 

**Acceptance Criteria**
- [ ] Identify the right people for the project 
- [ ] Agree on collective goals for alumni updates (i.e. what do we want to know)
- [ ] Agree on timeframe for alumni updates (i.e. how often we contact them)
- [ ] Create new tickets for next steps

 **Owner**
@MattCFry 

**Stakeholders**
@MattCFry @alecmccrindle @Barny-6 

**Approver**
@Barny-6

**Comment by MattCFry** [comment]
My thoughts: if we can refine 679 with #812. I can help us make regular progress with this.

If we want volunteers to support somehow, then we can ask Halden to support us in recruiting.
