### ISSUE TITLE
Create issues for 'Trainsition from Trainee to Grad'

### ISSUE THREAD

**Issue by emcglackenr1** [CodeYourFuture/CYF-Staff-Tickets#835]
### Background

Following the meeting on 07/03/2024, Dara and Barny discussed what further work needed to be completed regarding the transition between trainees and grads. See ticket #699

The below tasks were identified as important with regard to support course completers 

**Proposed Actions based on meeting**
- [x] Work out the graduation process and criteria - Handed over to Sally
- [x] Identify trainees who are still working towards their final projects - @emcglackenr1 
- [x] Create a guide for reviewing portfolio pages - Barny - already a ticket (https://github.com/CodeYourFuture/pd-prod-emp/issues/183)
- [x] Test the portfolio review process with a few volunteers and course completers  (https://github.com/CodeYourFuture/pd-prod-emp/issues/183)
- [x] Evaluate the CV feedback process and consider using pull requests - Barny (https://github.com/CodeYourFuture/PD-curriculum/issues/74) - Also being addressed by PD team
- [x] Communicate to trainees in each region of the value of the graduation criteria - no longer our work, handed over to Sally similar to point 1
- [x] Support trainees who are not prepared to meet the graduation criteria - Barny and Dara - [created milestone](https://github.com/CodeYourFuture/CYF-Staff-Tickets/milestone/34), action: think about it more and reconvene
- [x] Reach out to the West Midlands and Northwest communities to discuss engagement and job support - Barny and Dara (https://github.com/CodeYourFuture/Barny/issues/78)
- [x] Check in with trainees in Glasgow and confirm their plans - Dara
- [x] Start a second team for portfolio modules in the West Midlands and Northwest - Barny and Dara (https://github.com/CodeYourFuture/Barny/issues/78)

### Acceptance criteria

- [x] Meet to discuss - 2nd April 2024

- [x] Turn all of the actions into new issues, or link to current issues if they already exist on another board (@Barny-6 - you may have some of these elsewhere, since many are actions you mentioned)
- [x] Link issues to milestone

### Owner

@Barny-6 

### Stakeholder

@emcglackenr1

### Approver

N/A
